server:
  port: 5555
  servlet:
    context-path: /webqq
userConfig:
  qqNumber: 'xxxx'
  qqPasswd: 'xxxx'

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/webqqdb
    redis:
      repositories:
        enabled: false
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    password: 123456

socketio:
  port: 9999
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 10000
  pingTimeout: 60000
  pingInterval: 25000
  maxHttpContentLength: 1048576
  maxFramePayloadLength: 1048576

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG